Update gate jobs as per the 2025.1 cycle testing runtime
As per 2025.1 testing runtime[1], we need to test on Ubuntu
Noble (which will be taken care by depends-on tempest and devstack
patches to move base jobs to Noble) and at least single job to run on
Ubuntu Jammy (for smooth upgrade from previous releases).

This commit adds a new job to run on Jammy which can be removed
in the next cycle.

Also bump the hacking version to fix the pep8 erorr:
 -AttributeError: 'EntryPoints' object has no attribute 'get'

Closes-Bug: #2088356

Depends-On: https://review.opendev.org/c/openstack/tempest/+/932156

[1] https://governance.openstack.org/tc/reference/runtimes/2025.1.html

Change-Id: Ib4e2c089e7cd4ebb5aaccb9a747aaffe1618a5fa